-- Permissions seed data
-- Standard CRUD permissions for all modules

-- Organization Module Permissions
INSERT INTO `core_org_permissions` (`name`, `title`, `guard_name`, `created_at`, `updated_at`) VALUES
('app.tags.list', 'مشاهده لیست برچسب‌ها', 'web', NOW(), NOW()),
('app.tags.show', 'مشاهده جزئیات برچسب', 'web', NOW(), NOW()),
('app.tags.store', 'ایجاد برچسب', 'web', NOW(), NOW()),
('app.tags.update', 'ویرایش برچسب', 'web', NOW(), NOW()),
('app.tags.delete', 'حذف برچسب', 'web', NOW(), NOW()),
('app.tags.import', 'ایمپورت برچسب‌ها', 'web', NOW(), NOW()),
('app.tags.export', 'خروجی برچسب‌ها', 'web', NOW(), NOW()),

('org.users.list', 'مشاهده لیست کاربران', 'web', NOW(), NOW()),
('org.users.show', 'مشاهده جزئیات کاربر', 'web', NOW(), NOW()),
('org.users.store', 'ایجاد کاربر', 'web', NOW(), NOW()),
('org.users.update', 'ویرایش کاربر', 'web', NOW(), NOW()),
('org.users.delete', 'حذف کاربر', 'web', NOW(), NOW()),
('org.users.import', 'ایمپورت کاربران', 'web', NOW(), NOW()),
('org.users.export', 'خروجی کاربران', 'web', NOW(), NOW()),

('org.departments.list', 'مشاهده لیست دپارتمان‌ها', 'web', NOW(), NOW()),
('org.departments.show', 'مشاهده جزئیات دپارتمان', 'web', NOW(), NOW()),
('org.departments.store', 'ایجاد دپارتمان', 'web', NOW(), NOW()),
('org.departments.update', 'ویرایش دپارتمان', 'web', NOW(), NOW()),
('org.departments.delete', 'حذف دپارتمان', 'web', NOW(), NOW()),
('org.departments.import', 'ایمپورت دپارتمان‌ها', 'web', NOW(), NOW()),
('org.departments.export', 'خروجی دپارتمان‌ها', 'web', NOW(), NOW()),

('org.roles.list', 'مشاهده لیست نقش‌ها', 'web', NOW(), NOW()),
('org.roles.show', 'مشاهده جزئیات نقش', 'web', NOW(), NOW()),
('org.roles.store', 'ایجاد نقش', 'web', NOW(), NOW()),
('org.roles.update', 'ویرایش نقش', 'web', NOW(), NOW()),
('org.roles.delete', 'حذف نقش', 'web', NOW(), NOW()),
('org.roles.import', 'ایمپورت نقش‌ها', 'web', NOW(), NOW()),
('org.roles.export', 'خروجی نقش‌ها', 'web', NOW(), NOW()),

-- Documents Module Permissions
('documents.files.list', 'مشاهده لیست فایل‌ها', 'web', NOW(), NOW()),
('documents.files.show', 'مشاهده جزئیات فایل', 'web', NOW(), NOW()),
('documents.files.store', 'ایجاد فایل', 'web', NOW(), NOW()),
('documents.files.update', 'ویرایش فایل', 'web', NOW(), NOW()),
('documents.files.delete', 'حذف فایل', 'web', NOW(), NOW()),
('documents.files.import', 'ایمپورت فایل‌ها', 'web', NOW(), NOW()),
('documents.files.export', 'خروجی فایل‌ها', 'web', NOW(), NOW()),

('documents.folders.list', 'مشاهده لیست پوشه‌ها', 'web', NOW(), NOW()),
('documents.folders.show', 'مشاهده جزئیات پوشه', 'web', NOW(), NOW()),
('documents.folders.store', 'ایجاد پوشه', 'web', NOW(), NOW()),
('documents.folders.update', 'ویرایش پوشه', 'web', NOW(), NOW()),
('documents.folders.delete', 'حذف پوشه', 'web', NOW(), NOW()),
('documents.folders.import', 'ایمپورت پوشه‌ها', 'web', NOW(), NOW()),
('documents.folders.export', 'خروجی پوشه‌ها', 'web', NOW(), NOW()),

('bpms.workflow.list', 'مشاهده لیست جریان وظایف', 'web', NOW(), NOW()),
('bpms.workflow.show', 'مشاهده جزئیات جریان وظیفه', 'web', NOW(), NOW()),
('bpms.workflow.store', 'ایجاد جریان وظیفه', 'web', NOW(), NOW()),
('bpms.workflow.update', 'ویرایش جریان وظیفه', 'web', NOW(), NOW()),
('bpms.workflow.delete', 'حذف جریان وظیفه', 'web', NOW(), NOW()),
('bpms.workflow.import', 'ایمپورت جریان وظایف', 'web', NOW(), NOW()),
('bpms.workflow.export', 'خروجی جریان وظایف', 'web', NOW(), NOW()),

('bpms.workflow-state.list', 'مشاهده لیست وضعیت جریان وظیفه', 'web', NOW(), NOW()),
('bpms.workflow-state.show', 'مشاهده جزئیات وضعیت جریان وظیفه', 'web', NOW(), NOW()),
('bpms.workflow-state.store', 'ایجاد وضعیت جریان وظیفه', 'web', NOW(), NOW()),
('bpms.workflow-state.update', 'ویرایش وضعیت جریان وظیفه', 'web', NOW(), NOW()),
('bpms.workflow-state.delete', 'حذف وضعیت جریان وظیفه', 'web', NOW(), NOW()),
('bpms.workflow-state.import', 'ایمپورت وضعیت جریان وظیفه', 'web', NOW(), NOW()),
('bpms.workflow-state.export', 'خروجی وضعیت جریان وظیفه', 'web', NOW(), NOW()),

-- Tasks Module Permissions
('bpms.tasks.list', 'مشاهده لیست وظایف', 'web', NOW(), NOW()),
('bpms.tasks.show', 'مشاهده جزئیات وظیفه', 'web', NOW(), NOW()),
('bpms.tasks.store', 'ایجاد وظیفه', 'web', NOW(), NOW()),
('bpms.tasks.update', 'ویرایش وظیفه', 'web', NOW(), NOW()),
('bpms.tasks.delete', 'حذف وظیفه', 'web', NOW(), NOW()),
('bpms.tasks.import', 'ایمپورت وظایف', 'web', NOW(), NOW()),
('bpms.tasks.export', 'خروجی وظایف', 'web', NOW(), NOW()),

('bpms.watchlist.list', 'مشاهده لیست نظارت‌ها', 'web', NOW(), NOW()),
('bpms.watchlist.show', 'مشاهده جزئیات نظارت', 'web', NOW(), NOW()),
('bpms.watchlist.store', 'ایجاد نظارت', 'web', NOW(), NOW()),
('bpms.watchlist.update', 'ویرایش نظارت', 'web', NOW(), NOW()),
('bpms.watchlist.delete', 'حذف نظارت', 'web', NOW(), NOW()),
('bpms.watchlist.import', 'ایمپورت نظارت‌ها', 'web', NOW(), NOW()),
('bpms.watchlist.export', 'خروجی نظارت‌ها', 'web', NOW(), NOW()),

('bpms.followup.list', 'مشاهده لیست پیگیری‌ها', 'web', NOW(), NOW()),
('bpms.followup.show', 'مشاهده جزئیات پیگیری', 'web', NOW(), NOW()),
('bpms.followup.store', 'ایجاد پیگیری', 'web', NOW(), NOW()),
('bpms.followup.update', 'ویرایش پیگیری', 'web', NOW(), NOW()),
('bpms.followup.delete', 'حذف پیگیری', 'web', NOW(), NOW()),
('bpms.followup.import', 'ایمپورت پیگیری‌ها', 'web', NOW(), NOW()),
('bpms.followup.export', 'خروجی پیگیری‌ها', 'web', NOW(), NOW()),

('form-engine.form.list', 'مشاهده لیست فرم‌ها', 'web', NOW(), NOW()),
('form-engine.form.show', 'مشاهده جزئیات فرم', 'web', NOW(), NOW()),
('form-engine.form.store', 'ایجاد فرم', 'web', NOW(), NOW()),
('form-engine.form.update', 'ویرایش فرم', 'web', NOW(), NOW()),
('form-engine.form.delete', 'حذف فرم', 'web', NOW(), NOW()),
('form-engine.form.import', 'ایمپورت فرم‌ها', 'web', NOW(), NOW()),
('form-engine.form.export', 'خروجی فرم‌ها', 'web', NOW(), NOW()),

('form-engine.form-field.list', 'مشاهده لیست فیلدها', 'web', NOW(), NOW()),
('form-engine.form-field.show', 'مشاهده جزئیات فیلد', 'web', NOW(), NOW()),
('form-engine.form-field.store', 'ایجاد فیلد', 'web', NOW(), NOW()),
('form-engine.form-field.update', 'ویرایش فیلد', 'web', NOW(), NOW()),
('form-engine.form-field.delete', 'حذف فیلد', 'web', NOW(), NOW()),
('form-engine.form-field.import', 'ایمپورت فیلدها', 'web', NOW(), NOW()),
('form-engine.form-field.export', 'خروجی فیلدها', 'web', NOW(), NOW()),

('form-engine.field-option.list', 'مشاهده لیست آپشن فیلدها', 'web', NOW(), NOW()),
('form-engine.field-option.show', 'مشاهده جزئیات آپشن فیلد', 'web', NOW(), NOW()),
('form-engine.field-option.store', 'ایجاد آپشن فیلد', 'web', NOW(), NOW()),
('form-engine.field-option.update', 'ویرایش آپشن فیلد', 'web', NOW(), NOW()),
('form-engine.field-option.delete', 'حذف آپشن فیلد', 'web', NOW(), NOW()),
('form-engine.field-option.import', 'ایمپورت آپشن فیلدها', 'web', NOW(), NOW()),
('form-engine.field-option.export', 'خروجی آپشن فیلدها', 'web', NOW(), NOW()),

('form-engine.field-validation.list', 'مشاهده لیست ولیدیشن فیلدها', 'web', NOW(), NOW()),
('form-engine.field-validation.show', 'مشاهده جزئیات ولیدیشن فیلد', 'web', NOW(), NOW()),
('form-engine.field-validation.store', 'ایجاد ولیدیشن فیلد', 'web', NOW(), NOW()),
('form-engine.field-validation.update', 'ویرایش ولیدیشن فیلد', 'web', NOW(), NOW()),
('form-engine.field-validation.delete', 'حذف ولیدیشن فیلد', 'web', NOW(), NOW()),
('form-engine.field-validation.import', 'ایمپورت ولیدیشن فیلدها', 'web', NOW(), NOW()),
('form-engine.field-validation.export', 'خروجی ولیدیشن فیلدها', 'web', NOW(), NOW()),

('form-engine.submission.list', 'مشاهده لیست پاسخ‌ها', 'web', NOW(), NOW()),
('form-engine.submission.show', 'مشاهده جزئیات پاسخ', 'web', NOW(), NOW()),
('form-engine.submission.store', 'ایجاد پاسخ', 'web', NOW(), NOW()),
('form-engine.submission.update', 'ویرایش پاسخ', 'web', NOW(), NOW()),
('form-engine.submission.delete', 'حذف پاسخ', 'web', NOW(), NOW()),
('form-engine.submission.import', 'ایمپورت پاسخ‌ها', 'web', NOW(), NOW()),
('form-engine.submission.export', 'خروجی پاسخ‌ها', 'web', NOW(), NOW()),

('form-engine.submission.field-value.list', 'مشاهده لیست فیلدهای پاسخ', 'web', NOW(), NOW()),
('form-engine.submission.field-value.show', 'مشاهده جزئیات فیلدهای پاسخ', 'web', NOW(), NOW()),
('form-engine.submission.field-value.store', 'ایجاد فیلدهای پاسخ', 'web', NOW(), NOW()),
('form-engine.submission.field-value.update', 'ویرایش فیلدهای پاسخ', 'web', NOW(), NOW()),
('form-engine.submission.field-value.delete', 'حذف فیلدهای پاسخ', 'web', NOW(), NOW()),
('form-engine.submission.field-value.import', 'ایمپورت فیلدهای پاسخ', 'web', NOW(), NOW()),
('form-engine.submission.field-value.export', 'خروجی فیلدهای پاسخ', 'web', NOW(), NOW()),

('form-engine.validation-rule.list', 'مشاهده لیست قوانین اعتبار سنجی', 'web', NOW(), NOW()),
('form-engine.validation-rule.show', 'مشاهده جزئیات قوانین اعتبار سنجی', 'web', NOW(), NOW()),
('form-engine.validation-rule.store', 'ایجاد قوانین اعتبار سنجی', 'web', NOW(), NOW()),
('form-engine.validation-rule.update', 'ویرایش قوانین اعتبار سنجی', 'web', NOW(), NOW()),
('form-engine.validation-rule.delete', 'حذف قوانین اعتبار سنجی', 'web', NOW(), NOW()),
('form-engine.validation-rule.import', 'ایمپورت قوانین اعتبار سنجی', 'web', NOW(), NOW()),
('form-engine.validation-rule.export', 'خروجی قوانین اعتبار سنجی', 'web', NOW(), NOW());
