-- Permissions seed data
-- Standard CRUD permissions for all modules

-- Organization Module Permissions
INSERT INTO `core_org_permissions` (`name`, `title`, `guard_name`, `created_at`, `updated_at`) VALUES
('org.users.list', 'مشاهده لیست کاربران', 'web', NOW(), NOW()),
('org.users.show', 'مشاهده جزئیات کاربر', 'web', NOW(), NOW()),
('org.users.store', 'ایجاد کاربر', 'web', NOW(), NOW()),
('org.users.update', 'ویرایش کاربر', 'web', NOW(), NOW()),
('org.users.delete', 'حذف کاربر', 'web', NOW(), NOW()),
('org.users.import', 'ایمپورت داده کاربران', 'web', NOW(), NOW()),
('org.users.export', 'خروجی گرفتن کاربران', 'web', NOW(), NOW()),

('org.departments.list', 'مشاهده لیست دپارتمان‌ها', 'web', NOW(), NOW()),
('org.departments.show', 'مشاهده جزئیات دپارتمان', 'web', NOW(), NOW()),
('org.departments.store', 'ایجاد دپارتمان', 'web', NOW(), NOW()),
('org.departments.update', 'ویرایش دپارتمان', 'web', NOW(), NOW()),
('org.departments.delete', 'حذف دپارتمان', 'web', NOW(), NOW()),
('org.departments.import', 'ایمپورت داده دپارتمان‌ها', 'web', NOW(), NOW()),
('org.departments.export', 'خروجی گرفتن دپارتمان‌ها', 'web', NOW(), NOW()),

('org.roles.list', 'مشاهده لیست نقش‌ها', 'web', NOW(), NOW()),
('org.roles.show', 'مشاهده جزئیات نقش', 'web', NOW(), NOW()),
('org.roles.store', 'ایجاد نقش', 'web', NOW(), NOW()),
('org.roles.update', 'ویرایش نقش', 'web', NOW(), NOW()),
('org.roles.delete', 'حذف نقش', 'web', NOW(), NOW()),
('org.roles.import', 'ایمپورت داده نقش‌ها', 'web', NOW(), NOW()),
('org.roles.export', 'خروجی گرفتن نقش‌ها', 'web', NOW(), NOW()),

('org.job_positions.list', 'مشاهده لیست موقعیت‌های شغلی', 'web', NOW(), NOW()),
('org.job_positions.show', 'مشاهده جزئیات موقعیت شغلی', 'web', NOW(), NOW()),
('org.job_positions.store', 'ایجاد موقعیت شغلی', 'web', NOW(), NOW()),
('org.job_positions.update', 'ویرایش موقعیت شغلی', 'web', NOW(), NOW()),
('org.job_positions.delete', 'حذف موقعیت شغلی', 'web', NOW(), NOW()),
('org.job_positions.import', 'ایمپورت داده موقعیت‌های شغلی', 'web', NOW(), NOW()),
('org.job_positions.export', 'خروجی گرفتن موقعیت‌های شغلی', 'web', NOW(), NOW()),

-- Documents Module Permissions
('documents.files.list', 'مشاهده لیست فایل‌ها', 'web', NOW(), NOW()),
('documents.files.show', 'مشاهده جزئیات فایل', 'web', NOW(), NOW()),
('documents.files.store', 'ایجاد فایل', 'web', NOW(), NOW()),
('documents.files.update', 'ویرایش فایل', 'web', NOW(), NOW()),
('documents.files.delete', 'حذف فایل', 'web', NOW(), NOW()),
('documents.files.import', 'ایمپورت داده فایل‌ها', 'web', NOW(), NOW()),
('documents.files.export', 'خروجی گرفتن فایل‌ها', 'web', NOW(), NOW()),

('documents.folders.list', 'مشاهده لیست پوشه‌ها', 'web', NOW(), NOW()),
('documents.folders.show', 'مشاهده جزئیات پوشه', 'web', NOW(), NOW()),
('documents.folders.store', 'ایجاد پوشه', 'web', NOW(), NOW()),
('documents.folders.update', 'ویرایش پوشه', 'web', NOW(), NOW()),
('documents.folders.delete', 'حذف پوشه', 'web', NOW(), NOW()),
('documents.folders.import', 'ایمپورت داده پوشه‌ها', 'web', NOW(), NOW()),
('documents.folders.export', 'خروجی گرفتن پوشه‌ها', 'web', NOW(), NOW()),

-- Tasks Module Permissions
('tasks.tasks.list', 'مشاهده لیست وظایف', 'web', NOW(), NOW()),
('tasks.tasks.show', 'مشاهده جزئیات وظیفه', 'web', NOW(), NOW()),
('tasks.tasks.store', 'ایجاد وظیفه', 'web', NOW(), NOW()),
('tasks.tasks.update', 'ویرایش وظیفه', 'web', NOW(), NOW()),
('tasks.tasks.delete', 'حذف وظیفه', 'web', NOW(), NOW()),
('tasks.tasks.import', 'ایمپورت داده وظایف', 'web', NOW(), NOW()),
('tasks.tasks.export', 'خروجی گرفتن وظایف', 'web', NOW(), NOW()),

('tasks.task_categories.list', 'مشاهده لیست دسته‌بندی وظایف', 'web', NOW(), NOW()),
('tasks.task_categories.show', 'مشاهده جزئیات دسته‌بندی وظیفه', 'web', NOW(), NOW()),
('tasks.task_categories.store', 'ایجاد دسته‌بندی وظیفه', 'web', NOW(), NOW()),
('tasks.task_categories.update', 'ویرایش دسته‌بندی وظیفه', 'web', NOW(), NOW()),
('tasks.task_categories.delete', 'حذف دسته‌بندی وظیفه', 'web', NOW(), NOW()),
('tasks.task_categories.import', 'ایمپورت داده دسته‌بندی وظایف', 'web', NOW(), NOW()),
('tasks.task_categories.export', 'خروجی گرفتن دسته‌بندی وظایف', 'web', NOW(), NOW()),

-- Knowledge Module Permissions
('knowledge.experiences.list', 'مشاهده لیست تجربه‌ها', 'web', NOW(), NOW()),
('knowledge.experiences.show', 'مشاهده جزئیات تجربه', 'web', NOW(), NOW()),
('knowledge.experiences.store', 'ایجاد تجربه', 'web', NOW(), NOW()),
('knowledge.experiences.update', 'ویرایش تجربه', 'web', NOW(), NOW()),
('knowledge.experiences.delete', 'حذف تجربه', 'web', NOW(), NOW()),
('knowledge.experiences.import', 'ایمپورت داده تجربه‌ها', 'web', NOW(), NOW()),
('knowledge.experiences.export', 'خروجی گرفتن تجربه‌ها', 'web', NOW(), NOW()),

('knowledge.templates.list', 'مشاهده لیست قالب‌های تجربه', 'web', NOW(), NOW()),
('knowledge.templates.show', 'مشاهده جزئیات قالب تجربه', 'web', NOW(), NOW()),
('knowledge.templates.store', 'ایجاد قالب تجربه', 'web', NOW(), NOW()),
('knowledge.templates.update', 'ویرایش قالب تجربه', 'web', NOW(), NOW()),
('knowledge.templates.delete', 'حذف قالب تجربه', 'web', NOW(), NOW()),
('knowledge.templates.import', 'ایمپورت داده قالب‌های تجربه', 'web', NOW(), NOW()),
('knowledge.templates.export', 'خروجی گرفتن قالب‌های تجربه', 'web', NOW(), NOW()),

-- Finance Module Permissions
('finance.invoices.list', 'مشاهده لیست فاکتورها', 'web', NOW(), NOW()),
('finance.invoices.show', 'مشاهده جزئیات فاکتور', 'web', NOW(), NOW()),
('finance.invoices.store', 'ایجاد فاکتور', 'web', NOW(), NOW()),
('finance.invoices.update', 'ویرایش فاکتور', 'web', NOW(), NOW()),
('finance.invoices.delete', 'حذف فاکتور', 'web', NOW(), NOW()),
('finance.invoices.import', 'ایمپورت داده فاکتورها', 'web', NOW(), NOW()),
('finance.invoices.export', 'خروجی گرفتن فاکتورها', 'web', NOW(), NOW()),

('finance.payments.list', 'مشاهده لیست پرداخت‌ها', 'web', NOW(), NOW()),
('finance.payments.show', 'مشاهده جزئیات پرداخت', 'web', NOW(), NOW()),
('finance.payments.store', 'ایجاد پرداخت', 'web', NOW(), NOW()),
('finance.payments.update', 'ویرایش پرداخت', 'web', NOW(), NOW()),
('finance.payments.delete', 'حذف پرداخت', 'web', NOW(), NOW()),
('finance.payments.import', 'ایمپورت داده پرداخت‌ها', 'web', NOW(), NOW()),
('finance.payments.export', 'خروجی گرفتن پرداخت‌ها', 'web', NOW(), NOW()),

('finance.receivables.list', 'مشاهده لیست مطالبات', 'web', NOW(), NOW()),
('finance.receivables.show', 'مشاهده جزئیات مطالبات', 'web', NOW(), NOW()),
('finance.receivables.store', 'ایجاد مطالبات', 'web', NOW(), NOW()),
('finance.receivables.update', 'ویرایش مطالبات', 'web', NOW(), NOW()),
('finance.receivables.delete', 'حذف مطالبات', 'web', NOW(), NOW()),
('finance.receivables.import', 'ایمپورت داده مطالبات', 'web', NOW(), NOW()),
('finance.receivables.export', 'خروجی گرفتن مطالبات', 'web', NOW(), NOW()),

-- CRM Module Permissions
('crm.customers.list', 'مشاهده لیست مشتریان', 'web', NOW(), NOW()),
('crm.customers.show', 'مشاهده جزئیات مشتری', 'web', NOW(), NOW()),
('crm.customers.store', 'ایجاد مشتری', 'web', NOW(), NOW()),
('crm.customers.update', 'ویرایش مشتری', 'web', NOW(), NOW()),
('crm.customers.delete', 'حذف مشتری', 'web', NOW(), NOW()),
('crm.customers.import', 'ایمپورت داده مشتریان', 'web', NOW(), NOW()),
('crm.customers.export', 'خروجی گرفتن مشتریان', 'web', NOW(), NOW()),

('crm.leads.list', 'مشاهده لیست سرنخ‌ها', 'web', NOW(), NOW()),
('crm.leads.show', 'مشاهده جزئیات سرنخ', 'web', NOW(), NOW()),
('crm.leads.store', 'ایجاد سرنخ', 'web', NOW(), NOW()),
('crm.leads.update', 'ویرایش سرنخ', 'web', NOW(), NOW()),
('crm.leads.delete', 'حذف سرنخ', 'web', NOW(), NOW()),
('crm.leads.import', 'ایمپورت داده سرنخ‌ها', 'web', NOW(), NOW()),
('crm.leads.export', 'خروجی گرفتن سرنخ‌ها', 'web', NOW(), NOW()),

('crm.opportunities.list', 'مشاهده لیست فرصت‌ها', 'web', NOW(), NOW()),
('crm.opportunities.show', 'مشاهده جزئیات فرصت', 'web', NOW(), NOW()),
('crm.opportunities.store', 'ایجاد فرصت', 'web', NOW(), NOW()),
('crm.opportunities.update', 'ویرایش فرصت', 'web', NOW(), NOW()),
('crm.opportunities.delete', 'حذف فرصت', 'web', NOW(), NOW()),
('crm.opportunities.import', 'ایمپورت داده فرصت‌ها', 'web', NOW(), NOW()),
('crm.opportunities.export', 'خروجی گرفتن فرصت‌ها', 'web', NOW(), NOW()),

('crm.contacts.list', 'مشاهده لیست مخاطبین', 'web', NOW(), NOW()),
('crm.contacts.show', 'مشاهده جزئیات مخاطب', 'web', NOW(), NOW()),
('crm.contacts.store', 'ایجاد مخاطب', 'web', NOW(), NOW()),
('crm.contacts.update', 'ویرایش مخاطب', 'web', NOW(), NOW()),
('crm.contacts.delete', 'حذف مخاطب', 'web', NOW(), NOW()),
('crm.contacts.import', 'ایمپورت داده مخاطبین', 'web', NOW(), NOW()),
('crm.contacts.export', 'خروجی گرفتن مخاطبین', 'web', NOW(), NOW());
